### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by hienphan0111** [hienphan0111/Recipe-app#13]
Our group includes @hienphan0111 , @chepkok3 and @jodavid444 
[Click here](https://github.com/hienphan0111/Recipe-app/projects/1) to access GitHub project

**Comment by FrederickMih** [comment]
## Hi :raising_hand: :raising_hand: @hienphan0111, @chepkok3, @jodavid444  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 

:tada: :champagne: <img src="https://media.giphy.com/media/BjdEFIjaQv9bp1it9I/giphy.gif"  width ="160"><img> :tada: :champagne: 

## Highlights :green_circle: 

- Tasks have been distributed equally to all team members :+1: 



## Optional suggestions
**N/A**

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
